// This is a generated file.
// Generated by EnumGen, see https://github.com/Ryu0118/EnumGen

import Foundation

enum IBCompatibleViewType: String, Hashable {
    case view
    case imageView
    case button
    case tableView
    case label
    case progressView
    case collectionView
    case stackView
    case segmentedControl
    case slider
    case `switch`
    case activityIndicatorView
    case pageControl
    case stepper
    case tableViewCell
    case collectionViewCell
    case textView
    case textField
    case scrollView
    case pickerView
    case visualEffectView
    case mapView
    case mtkView
    case glkView
    case sceneKitView
    case skView
    case arskView
    case arscnView
    case wkWebView
    case arView
    case clLocationButton
    case navigationBar
    case toolbar
    case tabBar
    case searchBar
    case containerView
    case collectionViewCellContentView
    case collectionReusableView
}

extension IBCompatibleViewType: CaseIterable, CustomStringConvertible {
    
    var variableName: String {
        switch self {
        case .activityIndicatorView:
            return "indicatorView"
        case .collectionViewCell, .tableViewCell:
            return "cell"
        case .visualEffectView:
            return "effectView"
        case .wkWebView:
            return "webView"
        case .switch:
            return "swch"
        default:
            return self.rawValue
        }
    }
    
    var description: String {
        switch self {
        case .view:
            return "UIView"
        case .imageView:
            return "UIImageView"
        case .button:
            return "UIButton"
        case .tableView:
            return "UITableView"
        case .label:
            return "UILabel"
        case .progressView:
            return "UIProgressView"
        case .collectionView:
            return "UICollectionView"
        case .stackView:
            return "UIStackView"
        case .segmentedControl:
            return "UISegmentedControl"
        case .slider:
            return "UISlider"
        case .switch:
            return "UISwitch"
        case .activityIndicatorView:
            return "UIActivityIndicatorView"
        case .pageControl:
            return "UIPageControl"
        case .stepper:
            return "UIStepper"
        case .tableViewCell:
            return "UITableViewCell"
        case .collectionViewCell:
            return "UICollectionViewCell"
        case .textView:
            return "UITextView"
        case .textField:
            return "UITextField"
        case .scrollView:
            return "UIScrollView"
        case .pickerView:
            return "UIPickerView"
        case .visualEffectView:
            return "UIVisualEffectView"
        case .mapView:
            return "MKMapView"
        case .mtkView:
            return "MTKView"
        case .glkView:
            return "GLKView"
        case .sceneKitView:
            return "SCNView"
        case .skView:
            return "SKView"
        case .arskView:
            return "ARSKView"
        case .arscnView:
            return "ARSCNView"
        case .wkWebView:
            return "WKWebView"
        case .arView:
            return "ARView"
        case .clLocationButton:
            return "CLLocationButton"
        case .navigationBar:
            return "UINavigationBar"
        case .toolbar:
            return "UIToolBar"
        case .tabBar:
            return "UITabBar"
        case .searchBar:
            return "UISearchBar"
        case .containerView:
            return "UIViewController"
        case .collectionViewCellContentView:
            return "UIView"
        case .collectionReusableView:
            return "UICollectionReusableView"
        }
    }
}
