//
//  SwiftCodeGenerator.swift
//  
//
//  Created by Ryu on 2022/08/21.
//

import Foundation

class SwiftCodeGenerator {
    
    enum IBType {
        case storyboard(ibViewController: IBViewController)
        case xib(ibView: IBView)
    }
    
    let type: IBType
    let url: URL
    
    private var indentCount = 0
    
    init(url: URL, type: IBType) {
        self.type = type
        self.url = url
    }
    
    func generate() throws -> String {
        switch type {
        case .storyboard(let ibViewController):
            try generateViewController(ibViewController: ibViewController)
        case .xib(let ibView):
            generateView(ibView: ibView)
        }
    }
    
    private func generateViewController(ibViewController: IBViewController) throws -> String {
        guard let ibView = ibViewController.ibView else { throw "IBViewController property IBView is nil" }
        let fileHeader = generateFileHeader()
        let lines = ibView.subviews.map { $0.generateSwiftCode() }
    }
    
    private func generateView(ibView: IBView) -> String {
        ""
    }
    
    private func generateImport(dependencies: Dependencies) {
        
    }
    
    private func generateFileHeader() -> [Line] {
        """
        // \(url.lastPathComponent)
        //
        // This is a generated file.
        // Generated by MagicIB, see https://github.com/Ryu0118/MagicIB
        //
        """.buildLines(relatedVariableName: .fileHeader)
    }
    
}
